#!/usr/bin/env bash

log()  { printf "%b\n" "$*" ; return $? ; }
fail() { log "\nError: $*\n" ; exit 1 ; }

log 'Installing backdat...'
curl -sL https://raw.github.com/seryl/backdat/internal/bin/backdat | sudo tee /usr/local/bin/backdat >/dev/null
sudo chmod +x /usr/local/bin/backdat
log 'Backdat is installed; please configure your /etc/backdat.rb file.'
